apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        jsonData:
          timeInterval: "5s"
          queryTimeout: "60s"
          httpMethod: "POST"
      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger:16686
        jsonData:
          tracesToLogs:
            datasourceUid: 'loki'
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          maxLines: 1000
          derivedFields:
            - name: "traceID"
              matcherRegex: "traceID=(\\w+)"
              url: "$${__value.raw}"
              datasourceUid: "jaeger" 