apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-app
  labels:
    app: observability-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: observability-app
  template:
    metadata:
      labels:
        app: observability-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9464"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: observability-app
        image: observability-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 9464
          name: metrics
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          value: "development"
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: observability-config
              key: SERVICE_NAME
        - name: JAEGER_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: observability-config
              key: JAEGER_ENDPOINT
        # - name: OTLP_ENDPOINT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: observability-config
        #       key: OTLP_ENDPOINT
        - name: LOKI_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: observability-config
              key: LOKI_ENDPOINT
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5 