apiVersion: v1
kind: Service
metadata:
  name: observability-app
  labels:
    app: observability-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9464"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: observability-app
  ports:
  - port: 80
    targetPort: 3000
    name: http
  - port: 9464
    targetPort: 9464
    name: metrics
  type: ClusterIP 