apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - name: agent-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: agent-binary
    port: 6832
    protocol: UDP
    targetPort: 6832
  - name: collector
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: query
    port: 16686
    protocol: TCP
    targetPort: 16686
  type: ClusterIP 